version: "3.0"
services:
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ofek
      POSTGRES_PASSWORD: ofekgabay
      POSTGRES_DB: air_port
      volumes: postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  postgres: ~
