version: "3.0"
services:
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
  communication:
    container_name: communication
    restart: always
    # ports:
    #   - 5001:5001
    build: ./packages/communication
    networks:
      - airport-net
    env_file:
      - ".base.env"
  tower:
    container_name: tower
    restart: always
    build: ./packages/control-tower
    networks:
      - airport-net
    env_file:
      - ".base.env"
    depends_on:
      - communication
  client:
    container_name: client
    restart: always
    build: ./packages/client
    networks:
      - airport-net
    env_file:
      - ".base.env"
    depends_on:
      - communication
  generator:
    container_name: generator
    restart: always
    build: ./packages/generator
    networks:
      - airport-net
    env_file:
      - ".base.env"
    depends_on:
      - tower
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ofek
      POSTGRES_PASSWORD: ofekgabay
      POSTGRES_DB: air_port
      volumes: postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  postgres: ~
networks:
  airport-net:
    driver: bridge
